name: run-container

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/30 * * * *'
env:
  CHANNEL: ${{ secrets.CHANNEL }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
      
  build:
    name: Execute Container
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pull Latest Image
      run: docker pull ghcr.io/pknupper/steam-item-tracker:main

    - name: Run Container
      run: docker run ghcr.io/pknupper/steam-item-tracker:main -channel $CHANNEL -token $BOT_TOKEN